apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-app-config
  namespace: prod
data:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://relationnel-postgresql:5432/shopouille_catalog"
  QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  QUARKUS_ALLOWED_ORIGINS: "http://shopouille-prod.mathiaspuyfages.fr"