apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: traefik
  rules:
  - host: back-shopouille.mathiaspuyfages.fr
    http:
      paths:
      - backend:
          service:
            name: catalog-service
            port:
              number: 80
        path: /catalog
        pathType: Prefix
      - backend:
          service:
            name: cms-service
            port:
              number: 80
        path: /cms
        pathType: Prefix
