apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: devops-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      name: catalog
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/igdevx/shopouille-catalog:4c2222544360e92684e0105c73ddca17ae765fe2
        envFrom:
        - configMapRef:
            name: catalog-app-config
        - secretRef:
            name: catalog-db-secret
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"