apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: devops-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      name: catalog
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/igdevx/shopouille-cms:c5f06dd5f2ebe1625bd48c925260d3a8a884e07a
        envFrom:
        - configMapRef:
            name: cms-app-config
        - secretRef:
            name: cms-db-secret