apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  namespace: devops-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      name: catalog
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/igdevx/shopouille-cms:710c9a1ab00cfe1b320d63b4c38d211e4185fac7
        envFrom:
        - configMapRef:
            name: cms-app-config
        - secretRef:
            name: cms-db-secret