apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  namespace: devops-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      name: catalog
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/igdevx/shopouille-cms:0796974f579af61c03a4edef91eb6a5102a35802
        envFrom:
        - configMapRef:
            name: cms-app-config
        - secretRef:
            name: cms-db-secret