name: Promotes a specific docker image to the given tag

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV

      - name: Promote image matching this tagâ€™s commit
        env:
          IMAGE: ghcr.io/${{env.REPO_LOWER}}
          SHA: ${{ inputs.sha }}
          TAG: ${{ inputs.tag }}   # e.g. v1.2.3
        run: |
          docker pull $IMAGE:$SHA
          docker tag $IMAGE:$SHA $IMAGE:$TAG
          docker tag $IMAGE:$SHA $IMAGE:latest
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
