apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: prod
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "deleteDatasources": [
            {
                "name": "Loki",
                "orgId": 1
            }
        ],
        "datasources": [
            {
                "access": "proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.prod.svc:9090",
                "version": 1,
                "uid": "prometheus-prod"
            },
            {
                "access": "proxy",
                "editable": true,
                "name": "Loki-Prod",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki.prod.svc.cluster.local:3100",
                "version": 1,
                "uid": "loki-prod",
                "jsonData": {
                    "maxLines": 1000
                }
            }
        ]
    }
